### ISSUE TITLE
Fehler beim Aktivieren des Debian Service

### ISSUE THREAD

**Issue by tassilomoedl** [ipv64net/ipv64_client#19]
Wenn ich den Systemd Service für Node64 in Debian aktivieren will, bekomme ich diesen Fehler:
update-rc.d: error: node64_client Default-Start contains no runlevels, aborting.

**Comment by JonathanN1203** [comment]
schau ich mir später an

**Comment by tassilomoedl** [comment]
ok.

**Comment by JonathanN1203** [comment]
fehler sollte behoben sein, wget nochmal machen

**Comment by tassilomoedl** [comment]
Es funktioniert doch nicht, jetzt bekomme ich diesen Fehler:
The unit files have no installation config (WantedBy=, RequiredBy=, Also=,
Alias= settings in the [Install] section, and DefaultInstance= for template
units). This means they are not meant to be enabled using systemctl.
 
Possible reasons for having this kind of units are:
• A unit may be statically enabled by being symlinked from another unit's
  .wants/ or .requires/ directory.
• A unit's purpose may be to act as a helper for some other unit which has
  a requirement dependency on it.
• A unit may be started when needed via activation (socket, path, timer,
  D-Bus, udev, scripted systemctl call, ...).
• In case of template units, the unit is meant to be enabled with some
  instance name specified.

**Comment by JonathanN1203** [comment]
teste es bitte nochmal

**Comment by tassilomoedl** [comment]
Ja, jetzt geht es.
