### ISSUE TITLE
Probleme mit den Bereiben der Nod auf Banana Pi R2 

### ISSUE THREAD

**Issue by philipplindner-media-network** [ipv64net/ipv64_client#30]
Hallo,
Ich Habe von en Tollen Projekt gehört und dache probiers mit deine Banana Pi R2 mit OpenWRT 18.6.2
Folgene Pakete habe ich mit pip nachinstalire
pythonping-1.1.4
requests 2.27.1
multiping 1.1.2
dnspython 2.2.1
icmplib 2.1.1

Bei Der Instalation mit den requirement.txt ist bei mit folgender Felhel aufgetreten:
`root@OpenWrt:/opt/ipv64_client# pip3 install -r requirements.txt
Collecting pythonping~=1.1.4
  Downloading pythonping-1.1.4-py3-none-any.whl (16 kB)
ERROR: Could not find a version that satisfies the requirement requests~=2.28.2 (from versions: 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.6, 0.10.7, 0.10.8, 0.11.1, 0.11.2, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.13.8, 0.13.9, 0.14.0, 0.14.1, 0.14.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 2.0.0, 2.0.1, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2, 2.7.0, 2.8.0, 2.8.1, 2.9.0, 2.9.1, 2.9.2, 2.10.0, 2.11.0, 2.11.1, 2.12.0, 2.12.1, 2.12.2, 2.12.3, 2.12.4, 2.12.5, 2.13.0, 2.14.0, 2.14.1, 2.14.2, 2.15.1, 2.16.0, 2.16.1, 2.16.2, 2.16.3, 2.16.4, 2.16.5, 2.17.0, 2.17.1, 2.17.2, 2.17.3, 2.18.0, 2.18.1, 2.18.2, 2.18.3, 2.18.4, 2.19.0, 2.19.1, 2.20.0, 2.20.1, 2.21.0, 2.22.0, 2.23.0, 2.24.0, 2.25.0, 2.25.1, 2.26.0, 2.27.0, 2.27.1)
ERROR: No matching distribution found for requests~=2.28.2
`
nach den hänischen nachinstalliren mit pip3 kann den forlgend Felermeldung:
`IPv64.net - Initialisierung
Skip: IPv6 could not be resolved
Start ICMPv4 Task ID: FSTI2qUsRWCw
Traceback (most recent call last):
  File "/opt/ipv64_client/functions.py", line 36, in icmp
    response_list = ping(icmp_dst, count=icmp_count, interval=icmp_interval, timeout=icmp_timeout, payload_size=icmp_size, family=family)
  File "/usr/lib/python3.6/site-packages/icmplib/ping.py", line 147, in ping
    **kwargs)
TypeError: __init__() got an unexpected keyword argument 'family'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ipv64_client.py", line 62, in <module>
    task_result = functions.icmp(icmp_dst, icmp_size, icmp_count, icmp_interval, icmp_timeout, 4)
  File "/opt/ipv64_client/functions.py", line 44, in icmp
    packet_loss = response_list.packet_loss
UnboundLocalError: local variable 'response_list' referenced before assignment`
ich gehe jetzt davon aus das sie OpenWRT Software zu alt ist. Kann mann da was Machen.

**Comment by philipplindner-media-network** [comment]
Danke für den Tip wede es demnegst angehen

**Comment by philipplindner-media-network** [comment]
Abschlisenser Berich von der Banana Pi R2 vront. Das Update von OpenWRT 18.6.2 auf 19.07.10 hat leider nicht geklabet habe aber eine andere Linux Version Aufgespielt mit "Armbian 21.05.1" und der Normalen Debian 11 anleitung leuft es nun im Test.
Das einzige was nicht gehet ist der systemctl befel, ich sehe keine aktifiitäten via htop und ok, beim ausfüren ist folgener fehler zu lesen:
`systemctl enable --now node64_client.service ervice
Synchronizing state of node64_client.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable node64_client
update-rc.d: error: node64_client Default-Start contains no runlevels, aborting.`
 ich habe diesen nun manuel im screen laufen

**Comment by androidseb25** [comment]
hat sich erledigt
