### ISSUE TITLE
Python3.9 JSON Fehler

### ISSUE THREAD

**Issue by philipplindner-media-network** [ipv64net/ipv64_client#62]
Heute den 17.5.2023 ist beim neustarten der Nods volgener Fehler aufgetreten:
`root@IPv64-Node:/opt/ipv64_client# ls
README.md  devices  files  functions.py  ipv64_client.py  requirements.txt
root@IPv64-Node:/opt/ipv64_client# python3 ipv64_client.py kxxxxxxxt
IPv64.net - Initialisierung
using node_secret $kxxxxxxxt
Skip: IPv6 could not be resolved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ipv64_client/ipv64_client.py", line 42, in <module>
    x = x.json()
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by tassilomoedl** [comment]
Das ist von Dennis zurzeit so gewollt. Dennis bastelt gerade rum, deshalb gibt er bei den Task-Requests ein 404 zurück, was dann als JSON Fehler interpretiert wird.

**Comment by tassilomoedl** [comment]
stimmt, das wäre gut.

**Comment by JonathanN1203** [comment]
@philipplindner-media-network alle Fehlerfälle kann man leider nicht verhindern. Es ist auch nur ein temporäres Thema, aber kannst du gerne einbauen und per PR einbaun

**Comment by philipplindner-media-network** [comment]
PR erstelt
